### ISSUE TITLE
Error when running Primer: PydanticImportError 

### ISSUE THREAD

**Issue by pmalmgren** [oughtinc/ice#312]
While I trying to run the example from the hello world chapter in the [Ought Primer](https://primer.ought.org/chapters/hello-world) I consistently get this error:

```
Traceback (most recent call last):
  File "/Users/ptmalmgren/src/ice-demo/hello.py", line 3, in <module>
    from ice.recipe import recipe
  File "/Users/ptmalmgren/Library/Caches/pypoetry/virtualenvs/ice-demo-25sS_li7-py3.10/lib/python3.10/site-packages/ice/recipe.py", line 24, in <module>
    from pydantic import BaseSettings
  File "/Users/ptmalmgren/Library/Caches/pypoetry/virtualenvs/ice-demo-25sS_li7-py3.10/lib/python3.10/site-packages/pydantic/__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
  File "/Users/ptmalmgren/Library/Caches/pypoetry/virtualenvs/ice-demo-25sS_li7-py3.10/lib/python3.10/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.1.1/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.1.1/u/import-error
```

Because `setup.cfg` has no pinned version for Pydantic, I believe it is defaulting to the latest [Pydantic 2.1.1 release](https://github.com/pydantic/pydantic/releases/tag/v2.1.1) which contains backwards-incompatible changes.

**Comment by stuhlmueller** [comment]
Fixed in #314.
